In [26]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[2:] + 15

array([17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])